#undef TAPPING_TERM
#define TAPPING_TERM 120

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 40

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 4

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 30

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 150

#define NO_AUTO_SHIFT_NUMERIC
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "DRK3q/JaaGBZ"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 1

#define RGB_MATRIX_STARTUP_SPD 60

#define CUSTOM_SHIFT_KEYS_LAYER_MASK (1 << 0)